Pipeline:
  experiment_name: dummy
  Components:
    - name: ConceptStore
      component_config:
        mode: read
        document_class: ConceptML
        batch_size: 10
        concept_retriever: get_concepts
        query:
          taxonomy: EU Taxonomy
    - name: SentenceTransformerRetriever
      component_config:
        model_name_or_path: "sentence-transformers/all-MiniLM-L6-v2"
        content_field: description
        batch_size: 32
        show_progress_bar: True
    - name: OpenSearchStore
      component_config:
        mode: write
        index: concepts-dev
        document_class: ConceptML
        index_mapping: CONCEPTS_MAPPING
        exclude_fields:
          - status
          - scheme
          - child_of
          - parent_of
