FROM python:3.10.10

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y awscli

# set working directory
RUN mkdir /code
WORKDIR /code


# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Copy only the dependencies files to take advantage of caching
COPY pyproject.toml poetry.lock* /code/

# Install dependencies
RUN poetry install

# Copy the rest of the application code
COPY . /code/

CMD ["poetry", "run", "your_command_here"]



# Copy poetry.lock* in case it doesn't exist in the repo
COPY ./pyproject.toml ./poetry.lock* /code/

# Allow installing dev dependencies to run tests
RUN bash -c "pip install --upgrade pip"
RUN bash -c "poetry install --no-root"

COPY . /code/
