Pipeline:
  Config:
    experiment_name: eu_taxonomy_classifier_with_prompt
  Components:
    - name: OpenSearchStore
      component_config:
        mode: read
        batch_size: 5
        index: eu-taxonomy-insights-dev-v6
        document_class: AnnotatedInsight
        index_mapping: INSIGHTS_MAPPING
    # - name: SentenceTransformerRetriever
    #   component_config:
    #     model_name_or_path: "sentence-transformers/all-MiniLM-L6-v2"
    #     content_field: text
    #     batch_size: 32
    #     show_progress_bar: True
    - name: InsightClassifier
      component_config:
        model_name_or_path: "models/insights_classifier_v1/"
    - name: ESGRelatedConceptsClassifier
      component_config:
        # for dev using smaller model, actual model is: facebook/bart-large-mnli
        model_name_or_path: facebook/bart-large-mnli
        prompt: The company does {}
        nli_threshold: 0.2
        top_k: 10
        concept_datastore:
          Pipeline:
            Components:
              - name: OpenSearchStore
                component_config:
                  mode: read
                  index: concepts-dev
                  filters:
                    taxonomy:
                      label: "EU Taxonomy"
                  document_class: SimpleConcept
                  index_mapping: CONCEPTS_MAPPING
    - name: OpenSearchStore
      component_config:
        mode: write
        batch_size: 5
        index: eu-taxonomy-insights-dev-v6
        document_class: AnnotatedInsight
        index_mapping: INSIGHTS_MAPPING
