wandb_version: 1

header:
  desc: null
  value: Text Property Outliers
name:
  desc: null
  value: Text Property Outliers
params:
  desc: null
  value:
    n_show_top: 5
    iqr_percentiles:
    - 25
    - 75
    iqr_scale: 2
    sharp_drop_ratio: 0.9
    min_samples: 10
summary:
  desc: null
  value: Find outliers with respect to the given properties.
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.34.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702276295.393551
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 65
      - 71
      - 75
      - 91
      - 93
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 65
      - 71
      - 75
      - 91
      - 93
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.10.9
      5: 0.16.0
      6: 4.34.1
      8:
      - 4
      - 5
      9:
        2: Deepchecks
      13: darwin-arm64
