Pipeline:
  Config:
    experiment_name: eu_taxonomy_classifier_api
  Components:
    - name: ExtractScraperHTML
    - name: ParagraphProcessor
    - name: SentenceTransformerRetriever
      component_config:
        model_name_or_path: "sentence-transformers/all-MiniLM-L6-v2"
        batch_size: 32
        show_progress_bar: True
    - name: EUTaxonomyClassifier
      component_config:
        model_name_or_path: cross-encoder/nli-deberta-v3-xsmall #facebook/bart-large-mnli
        argmax_prediction: false
        classification_threshold: 0.2
        eu_taxonomy_file_url: https://ec.europa.eu/sustainable-finance-taxonomy/assets/documents/taxonomy.xlsx
        concept_filter_type: dense_concept_retriever
        top_k: 5
        concept_datastore:
          Pipeline:
            Components:
              - name: OpenSearchStore
                component_config:
                  mode: read
                  index: concepts-dev
                  document_class: SimpleConcept
                  index_mapping: CONCEPTS_MAPPING
