from smart_evidence.components.processors.document_processor import DocumentProcessor
from smart_evidence.components.processors.generate_annotation_tasks import (
    GenerateAnnotationTasks,
)
from smart_evidence.components.processors.paragraph_processor import ParagraphProcessor
from smart_evidence.components.processors.text_extractor import TextExtractor
from smart_evidence.components.processors.extract_s3_html import ExtractHTML
from smart_evidence.components.processors.extract_scraper_html import ExtractScraperHTML
from smart_evidence.components.processors.aggregate_content import AggregateContent
