Pipeline:
  Config:
    experiment_name: eu_taxonomy_classifier_api
  Components:
    - name: ExtractScraperHTML
    - name: ParagraphProcessor
      component_config:
        paragraph_marker: double_break
    - name: SentenceTransformerRetriever
      component_config:
        model_name_or_path: models/all-MiniLM-L6-v2
        batch_size: 32
        show_progress_bar: True
    - name: ESGRelatedConceptsClassifier
      component_config:
        # for dev using smaller model, actual model is: facebook/bart-large-mnli
        model_name_or_path: models/nli-deberta-v3-xsmall/ #facebook/bart-large-mnli
        prompt: The company does {}
        nli_threshold: 0.2
        similarity_threshold: 0.8
        top_k: 5
        concept_datastore:
          Pipeline:
            Components:
              - name: OpenSearchStore
                component_config:
                  filters:
                    taxonomy:
                      label: "EU Taxonomy"
                  mode: read
                  index: concepts-eu-taxonomy-v1
                  document_class: SimpleConcept
                  index_mapping: CONCEPTS_MAPPING
