name: test_gpu
on:
  push:
    paths:
      - 'Services/DVC/cml_gpu_test/**'

jobs:
  run:
    runs-on: [self-hosted,cml,gpu]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CODEBLOCK ="\`\`\`"
          echo $CODEBLOCK > report.md
          nvidia-smi >> report.md
          echo $CODEBLOCK >> report.md
          cml-send-comment report.md
