name: auto-testing
on:
  push:
    paths:
      - 'Services/DVC/**'

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: sanity-check
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip3 install -r Services/DVC/model_requirements.txt
          python3 Services/DVC/test.py